import {Dimensions, StyleSheet} from "react-native";
import {Colors as colors} from "@/components/design/colors";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  container__dark: {
    flex: 1,
    backgroundColor: "#0A0A0A",
  },
  header: {
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 24,
    position: "relative",
    overflow: "hidden",
    height: 140,
  },
  headerGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  workspaceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  workspaceTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "600",
  },
  profileImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#1C4A5A",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  searchContainer: {
    flexDirection: "row",
    gap: 8,
  },
  searchBar: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchPlaceholder: {
    color: "#FFFFFF",
    opacity: 0.8,
  },
  filterButton: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 8,
    padding: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1C4A5A",
    marginBottom: 16,
  },
  sectionTitle__dark: {
    fontSize: 16,
    fontWeight: "600",
    color: "#8EACB7",
    marginBottom: 16,
  },
  quickActionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  quickActionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    width: "47%",
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#E5E5E5",
    elevation: 0,
    shadowOpacity: 0,
  },
  quickActionCard__dark: {
    backgroundColor: "#171717",
    borderRadius: 12,
    padding: 16,
    width: "47%",
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#262626",
    elevation: 0,
    shadowOpacity: 0,
  },
  quickActionLeftContent: {
    flexDirection: "column",
    gap: 8,
  },
  iconContainer: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  quickActionCount: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1C4A5A",
    alignSelf: "flex-start",
  },
  quickActionCount__dark: {
    fontSize: 20,
    fontWeight: "600",
    color: "#8EACB7",
    alignSelf: "flex-start",
  },
  quickActionTitle: {
    fontSize: 14,
    color: "#4A6572",
  },
  quickActionTitle__dark: {
    fontSize: 14,
    color: "#A0B3BC",
  },
  categoriesList: {
    gap: 16,
  },
  categoryItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  categoryItem__dark: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#262626",
  },
  categoryIconContainer: {
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  categoryTitle: {
    fontSize: 15,
    fontWeight: "500",
    color: "#1C4A5A",
  },
  categoryTitle__dark: {
    fontSize: 15,
    fontWeight: "500",
    color: "#8EACB7",
  },
  searchIconContainer: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  filterIconContainer: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  emoji: {
    fontSize: 24,
    opacity: 0.9,
    color: "#222222",
    includeFontPadding: false,
  },
  emoji__dark: {
    fontSize: 24,
    opacity: 0.9,
    color: "#F0F0F0",
    includeFontPadding: false,
  },
  categoryEmoji: {
    fontSize: 14,
    width: 32,
    opacity: 0.9,
    color: "#222222",
    includeFontPadding: false,
    textAlign: "center",
  },
  categoryEmoji__dark: {
    fontSize: 14,
    width: 32,
    opacity: 0.9,
    color: "#F0F0F0",
    includeFontPadding: false,
    textAlign: "center",
  },
  categoriesContainer: {
    backgroundColor: "transparent",
    borderRadius: 16,
    padding: 8,
    gap: 4,
    borderWidth: 1,
    borderColor: "#E5E5E5",
  },
  categoriesContainer__dark: {
    backgroundColor: "transparent",
    borderRadius: 16,
    padding: 8,
    gap: 4,
    borderWidth: 1,
    borderColor: "#262626",
  },
  workspaceSelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-start",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    marginTop: 80,
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalContent__dark: {
    backgroundColor: "#1E1E1E",
    marginTop: 80,
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3.84,
    elevation: 5,
  },
  workspaceOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  workspaceOptionSelected: {
    backgroundColor: "#F5F5F5",
  },
  workspaceOptionSelected__dark: {
    backgroundColor: "#262626",
  },
  workspaceOptionText: {
    fontSize: 16,
    color: "#1C4A5A",
  },
  workspaceOptionText__dark: {
    fontSize: 16,
    color: "#8EACB7",
  },
  workspaceOptionTextSelected: {
    color: "#4A6572",
    fontWeight: "600",
  },
  workspaceOptionTextSelected__dark: {
    color: "#A0B3BC",
    fontWeight: "600",
  },
  avatarFallback: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#1C4A5A",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  scrollView: {
    flex: 1,
  },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    zIndex: 999,
  },
  fabButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.TextColor.LignMainColor,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  loaderStyle: {
    height: 30,
    flex: 0,
    alignSelf: 'center',
  },
});
