import {StyleSheet} from "react-native";
import {scaleHeight, scaleWidth} from "../design/scale";
import {getFont} from "../design/fonts/fonts";
import {EFontWeight} from "../design/fonts/types";
import {Colors} from "../design/colors";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    borderBottomColor: Colors.OtherColor.InputGrayBorder,
    borderBottomWidth: 1,
    paddingVertical: scaleHeight(13),
  },
  container__dark: {
    width: "100%",
    borderBottomColor: "#262626",
    borderBottomWidth: 1,
    paddingVertical: scaleHeight(13),
  },
  content: {
    gap: scaleHeight(6),
    backgroundColor: Colors.tailwindColors.neutral["0"],
    padding: 16,
  },
  content__dark: {
    gap: scaleHeight(6),
    backgroundColor: "#171717",
    padding: 16,
  },
  contentContainer: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.tailwindColors.neutral["300"],
    borderRadius: 12,
  },
  contentContainer__dark: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#262626",
    borderRadius: 12,
  },
  linkTitle: {
    ...getFont(EFontWeight.Medium),
    fontSize: scaleHeight(16),
    lineHeight: scaleHeight(21),
    color: Colors.TextColor.DarkHeadingColor,
    maxHeight: scaleWidth(244),
  },
  linkTitle__dark: {
    ...getFont(EFontWeight.Medium),
    fontSize: scaleHeight(16),
    lineHeight: scaleHeight(21),
    color: "#FFFFFF",
    maxHeight: scaleWidth(244),
  },
  urlBox: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: scaleWidth(4),
  },
  url: {
    fontSize: scaleHeight(12),
    color: Colors.tailwindColors.neutral["500"],
  },
  url__dark: {
    fontSize: scaleHeight(12),
    color: "#8F8F8F",
  },
  noteContainer: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: scaleWidth(4),
  },
  linkDescription: {
    ...getFont(EFontWeight.Medium),
    color: Colors.tailwindColors.neutral["500"],
    // width: scaleWidth(244),
    fontSize: scaleHeight(12),
  },
  linkDescription__dark: {
    ...getFont(EFontWeight.Medium),
    color: "#8F8F8F",
    // width: scaleWidth(244),
    fontSize: scaleHeight(12),
  },
  bottomBar: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  elapsedTime: {
    ...getFont(EFontWeight.Regular),
    fontSize: scaleHeight(12),
    color: Colors.tailwindColors.neutral["500"],
  },
  elapsedTime__dark: {
    ...getFont(EFontWeight.Regular),
    fontSize: scaleHeight(12),
    color: "#8F8F8F",
  },
  imageContainer: {
    backgroundColor: Colors.tailwindColors.neutral["0"],
    paddingTop: 8,
  },
  imageContainer__dark: {
    backgroundColor: "#171717",
    paddingTop: 8,
  },
  image: {
    width: "95%",
    aspectRatio: 16 / 9,
    borderRadius: 12,
    marginHorizontal: "2.5%",
    // transform: [{ translateY: 24 }, { rotateX: "-25deg" }],
  },
  bottomBarButtons: {
    marginTop: 8,
    gap: scaleWidth(4),
    flexDirection: "row",
  },
  detailsText: {
    color: Colors.TextColor.CardButtonsText,
    ...getFont(EFontWeight.Regular),
    fontSize: scaleHeight(10),
    lineHeight: scaleHeight(24),
  },
  detailsText__dark: {
    color: "#8EACB7",
    ...getFont(EFontWeight.Regular),
    fontSize: scaleHeight(10),
    lineHeight: scaleHeight(24),
  },
  avatarContainer: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.OtherColor.BorderGrayColor,
  },
  avatarContainer__dark: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#262626",
  },
  avatar: {
    width: 20,
    height: 20,
  },
  detailsOpenButton: {
    height: scaleHeight(24),
    paddingHorizontal: scaleWidth(5),
    backgroundColor: Colors.ButtonsColor.GrayBackButton,
    flexDirection: "row",
    gap: scaleWidth(7),
    alignItems: "center",
    borderRadius: 8,
  },
  detailsOpenButton__dark: {
    height: scaleHeight(24),
    paddingHorizontal: scaleWidth(5),
    backgroundColor: "#333333",
    flexDirection: "row",
    gap: scaleWidth(7),
    alignItems: "center",
    borderRadius: 8,
  },
  iconPlaceholder: {
    width: 50,
    height: 50,
  },
  bottomStyles: {
    backgroundColor: Colors.tailwindColors.neutral["0"],
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    gap: 8,
  },
  bottomStyles__dark: {
    backgroundColor: "#171717",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-end",
    gap: 8,
  },
  readerButton: {
    position: "absolute",
    top: 26,
    right: 13,
    zIndex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 6,
    padding: 6,
    boxShadow: "0 8px 16px rgba(0, 0, 0, 0.2)",
  },
  readerButton__dark: {
    position: "absolute",
    top: 26,
    right: 13,
    zIndex: 1,
    backgroundColor: "rgba(50, 50, 50, 0.9)",
    borderRadius: 6,
    padding: 6,
    boxShadow: "0 8px 16px rgba(0, 0, 0, 0.2)",
  },
  webViewButton: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 10,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 10,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  webViewButton__dark: {
    backgroundColor: "rgba(40, 40, 40, 0.8)",
    shadowColor: "#000",
  },
  readerContainer: {
    flex: 1,
    backgroundColor: Colors.tailwindColors.neutral["50"],
  },
  closeReaderButton: {
    padding: 8,
  },
  reader: {
    flex: 1,
    backgroundColor: Colors.tailwindColors.neutral["50"],
    marginTop: 60,
  },
  readerHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.tailwindColors.neutral["0"],
    borderBottomWidth: 1,
    borderBottomColor: Colors.tailwindColors.neutral["200"],
    height: 60,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 999,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  readerTitle: {
    ...getFont(EFontWeight.Medium),
    fontSize: 14,
    flex: 1,
    marginLeft: 12,
    marginRight: 16,
    color: Colors.TextColor.DarkHeadingColor,
    textAlignVertical: "center",
  },
  readerContentStyle: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 40,
    maxWidth: 680,
    alignSelf: "center",
    width: "100%",
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  ttsButton: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.tailwindColors.neutral["0"],
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 1000,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
    paddingHorizontal: 8,
    gap: 4,
    textAlignVertical: "center",
  },
  editButtonText: {
    ...getFont(EFontWeight.Regular),
    fontSize: 12,
    marginTop: 2,
    color: Colors.tailwindColors.neutral["700"],
  },
});
