import {StyleSheet} from "react-native";
import {Colors} from "@/components/design/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  container__dark: {
    flex: 1,
    backgroundColor: "#0A0A0A",
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: '#fff',
  },
  header__dark: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#262626',
    backgroundColor: '#0A0A0A',
  },
  headerLogo: {
    width: 24,
    height: 24,
    marginRight: 8,
    borderRadius: 6,
  },
  headerIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#f3f3f3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#333",
    letterSpacing: 0.2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitleText: {
    fontSize: 17,
    fontWeight: "600",
    color: "#333",
  },
  headerTitleText__dark: {
    fontSize: 17,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#f7f7f7',
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerButton__dark: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#262626',
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contextButton: {
    backgroundColor: '#f0f7ff',
  },
  messagesContainer: {
    flex: 1,
  },
  messagesContent: {
    padding: 16,
    paddingBottom: 40,
    paddingRight: 12,
  },
  emptyMessagesContent: {
    flex: 1,
    justifyContent: 'center',
  },
  messageBubble: {
    maxWidth: '85%',
    padding: 14,
    borderRadius: 18,
    marginBottom: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#f0f0f0',  // Light neutral gray
    borderBottomRightRadius: 6,
    marginTop: 8,
    marginBottom: 16,
    shadowColor: 'rgba(0,0,0,0.08)',
    paddingVertical: 9,
  },
  userMessage__dark: {
    backgroundColor: '#293F4E',
    alignSelf: 'flex-end',
    borderBottomRightRadius: 6,
    marginTop: 8,
    marginBottom: 16,
    shadowColor: 'rgba(0,0,0,0.08)',
    paddingVertical: 9,
  },
  aiMessage: {
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
    borderBottomLeftRadius: 0,
    marginLeft: 0,
    maxWidth: '92%',
    marginTop: 4,
    shadowOpacity: 0,
    elevation: 0,
    borderWidth: 0,
    padding: 10,
    paddingTop: 0,
    paddingLeft: 0,
  },
  aiMessage__dark: {
    backgroundColor: '#171717',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 0,
    marginLeft: 0,
    maxWidth: '92%',
    marginTop: 4,
    shadowOpacity: 0,
    elevation: 0,
    borderWidth: 0,
    padding: 10,
    paddingTop: 0,
    paddingLeft: 0,
  },
  assistantMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingRight: 16,
    marginTop: 4,
  },
  assistantAvatarContainer: {
    marginRight: 10,
    marginTop: 2,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assistantAvatarContainer__dark: {
    marginRight: 10,
    marginTop: 2,
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assistantAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  messageText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
  },
  userMessageText: {
    color: '#333',  // Dark text for light background
  },
  userMessageText__dark: {
    color: '#E5E5E5',
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 16,
    paddingRight: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    backgroundColor: '#fff',
    alignItems: 'center',
    width: '100%',
  },
  inputContainer__dark: {
    flexDirection: 'row',
    padding: 16,
    paddingRight: 16,
    borderTopWidth: 1,
    borderTopColor: '#262626',
    backgroundColor: '#0A0A0A',
    alignItems: 'center',
    width: '100%',
  },
  input: {
    flex: 1,
    backgroundColor: '#f7f7f7',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingRight: 52,
    fontSize: 16,
    maxHeight: 120,
    minHeight: 48,
    color: '#333',
    marginRight: 0,
  },
  input__dark: {
    flex: 1,
    backgroundColor: '#262626',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingRight: 52,
    fontSize: 16,
    maxHeight: 120,
    minHeight: 48,
    color: '#E5E5E5',
    marginRight: 0,
  },
  sendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.TextColor.LignMainColor,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 8,
    bottom: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sendButtonDisabled: {
    backgroundColor: '#f0f0f0',
    shadowOpacity: 0,
    elevation: 0,
  },
  sendButtonDisabled__dark: {
    backgroundColor: '#444',
    shadowOpacity: 0,
    elevation: 0,
  },
  loadingBubbles: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  bubble: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#888',
    margin: 2,
    opacity: 0.6,
  },
  bubble__dark: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#555',
    margin: 2,
    opacity: 0.6,
  },
  bubble1: {
    opacity: 0.4,
  },
  bubble2: {
    opacity: 0.7,
  },
  bubble3: {
    opacity: 1,
  },
  loadingBubbleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  thinkingContainer: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingVertical: 0,
    marginLeft: 2,
  },
  thinkingTextContainer: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 4,
    padding: 2,
  },
  thinkingTextContainer__dark: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 4,
    padding: 2,
  },
  thinkingText: {
    fontSize: 16,
    color: '#888',
    fontWeight: '500',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  thinkingText__dark: {
    fontSize: 16,
    color: '#A0B3BC',
    fontWeight: '500',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  badgeContainer: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Colors.TextColor.LignMainColor,
    borderRadius: 10,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  drawerContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    height: '90%',
    paddingBottom: 0,
  },
  drawerContainer__dark: {
    backgroundColor: '#0A0A0A',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    height: '90%',
    paddingBottom: 0,
  },
  drawerContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  drawerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  drawerTitle__dark: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E5E5',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  searchContainer__dark: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#262626',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: 48,
    fontSize: 16,
    color: '#333',
  },
  searchInput__dark: {
    flex: 1,
    height: 48,
    fontSize: 16,
    color: '#E5E5E5',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
  },
  emptyText__dark: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
  },
  linksList: {
    flex: 1,
    marginBottom: 0,
  },
  linksListContent: {
    paddingBottom: 0,
  },
  linkItem: {
    flexDirection: 'row',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#f8f8f8',
    alignItems: 'center',
  },
  linkItem__dark: {
    flexDirection: 'row',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#171717',
    alignItems: 'center',
  },
  selectedLinkItem: {
    backgroundColor: '#edf7ff',
  },
  selectedLinkItem__dark: {
    backgroundColor: '#293F4E',
  },
  linkContent: {
    flex: 1,
    marginRight: 8,
  },
  linkTitle: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
    marginBottom: 4,
  },
  linkTitle__dark: {
    fontSize: 15,
    fontWeight: '500',
    color: '#E5E5E5',
    marginBottom: 4,
  },
  linkDescription: {
    fontSize: 13,
    color: '#666',
  },
  linkDescription__dark: {
    fontSize: 13,
    color: '#A0B3BC',
  },
  checkboxContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxContainer__dark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#555',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A0A0A',
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  addButton__dark: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#262626',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  inputWithButton: {
    marginRight: 0,
  },
  markdownLink: {
    fontWeight: '500',
    color: '#3366cc',
    textDecorationLine: "underline",
  },
  markdownCodeInline: {
    backgroundColor: '#f5f5f5',
    fontSize: 14,
    padding: 2,
    paddingHorizontal: 4,
    borderRadius: 3,
    color: '#555',
  },
  markdownCodeBlock: {
    backgroundColor: '#f5f5f5',
    fontSize: 13,
    padding: 10,
    borderRadius: 4,
    marginVertical: 6,
    color: '#555',
  },
  markdownList: {
    marginLeft: 0,
  },
  markdownListIcon: {
    fontSize: 14,
    color: '#555',
  },
  markdownBold: {
    fontWeight: '500',
  },
  markdownItalic: {
    fontStyle: "italic",
    color: '#444',
  },
  markdownH1: {
    fontSize: 22,
    fontWeight: '600',
    color: '#333',
    marginTop: 16,
    marginBottom: 8,
    lineHeight: 28,
  },
  markdownH2: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    marginTop: 14,
    marginBottom: 8,
    lineHeight: 26,
  },
  markdownH3: {
    fontSize: 18,
    fontWeight: '500',
    color: '#333',
    marginTop: 12,
    marginBottom: 8,
    lineHeight: 24,
  },
  markdownH4: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginTop: 10,
    marginBottom: 6,
    lineHeight: 22,
  },
  markdownH5: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
    marginTop: 8,
    marginBottom: 6,
    lineHeight: 20,
  },
  markdownH6: {
    fontSize: 14,
    fontWeight: '500',
    color: '#444',
    marginTop: 8,
    marginBottom: 6,
    lineHeight: 20,
  },
  markdownParagraph: {
    marginVertical: 4,
    lineHeight: 22,
    marginTop: 0,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoContainer: {
    width: 100,
    height: 100,
    marginBottom: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 20,
    padding: 20,
  },
  logo: {
    width: '100%',
    height: '100%',
  },
  emptyStateTitle: {
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 12,
    color: '#333',
    textAlign: 'center',
  },
  emptyStateTitle__dark: {
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 12,
    color: '#E5E5E5',
    textAlign: 'center',
  },
  emptyStateDescription: {
    fontSize: 16,
    marginBottom: 32,
    color: '#666',
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
  },
  emptyStateDescription__dark: {
    fontSize: 16,
    marginBottom: 32,
    color: '#A0B3BC',
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 300,
  },
  suggestionsContainer: {
    width: '100%',
    maxWidth: 350,
    marginTop: 10,
  },
  suggestionButton: {
    backgroundColor: '#f8f8f8',
    padding: 14,
    borderRadius: 10,
    width: '100%',
    marginBottom: 8,
    borderWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  suggestionButton__dark: {
    backgroundColor: '#171717',
    padding: 14,
    borderRadius: 10,
    width: '100%',
    marginBottom: 8,
    borderWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  suggestionIcon: {
    marginRight: 10,
  },
  suggestionText: {
    fontSize: 15,
    color: '#555',
    fontWeight: '400',
    flex: 1,
  },
  suggestionText__dark: {
    fontSize: 15,
    color: '#A0B3BC',
    fontWeight: '400',
    flex: 1,
  },
}); 